"""add photo fields to boxes

Revision ID: 545da5e7c836
Revises: 6b35e2dc89ef
Create Date: 2026-09-17 18:35:22.518473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545da5e7c836'
down_revision: Union[str, None] = '6b35e2dc89ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxes', sa.Column('photo_path', sa.String(length=512), nullable=True))
    op.add_column('boxes', sa.Column('photo_thumbnail_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boxes', 'photo_thumbnail_path')
    op.drop_column('boxes', 'photo_path')
    # ### end Alembic commands ###