"""initial schema

Revision ID: 6b35e2dc89ef
Revises: 
Create Date: 2026-09-15 22:59:38.955382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b35e2dc89ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_is_deleted'), 'categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_created_at'), 'conditions', ['created_at'], unique=False)
    op.create_index(op.f('ix_conditions_is_deleted'), 'conditions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_conditions_name'), 'conditions', ['name'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_created_at'), 'locations', ['created_at'], unique=False)
    op.create_index(op.f('ix_locations_is_deleted'), 'locations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('packagings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packagings_created_at'), 'packagings', ['created_at'], unique=False)
    op.create_index(op.f('ix_packagings_is_deleted'), 'packagings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_packagings_name'), 'packagings', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boxes_created_at'), 'boxes', ['created_at'], unique=False)
    op.create_index(op.f('ix_boxes_is_deleted'), 'boxes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_boxes_location_id'), 'boxes', ['location_id'], unique=False)
    op.create_index(op.f('ix_boxes_name'), 'boxes', ['name'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('packaging_id', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('photo_thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['packaging_id'], ['packagings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_box_id'), 'items', ['box_id'], unique=False)
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_condition_id'), 'items', ['condition_id'], unique=False)
    op.create_index(op.f('ix_items_created_at'), 'items', ['created_at'], unique=False)
    op.create_index(op.f('ix_items_is_deleted'), 'items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_items_location_id'), 'items', ['location_id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_location_id'), table_name='items')
    op.drop_index(op.f('ix_items_is_deleted'), table_name='items')
    op.drop_index(op.f('ix_items_created_at'), table_name='items')
    op.drop_index(op.f('ix_items_condition_id'), table_name='items')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_index(op.f('ix_items_box_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_boxes_name'), table_name='boxes')
    op.drop_index(op.f('ix_boxes_location_id'), table_name='boxes')
    op.drop_index(op.f('ix_boxes_is_deleted'), table_name='boxes')
    op.drop_index(op.f('ix_boxes_created_at'), table_name='boxes')
    op.drop_table('boxes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_packagings_name'), table_name='packagings')
    op.drop_index(op.f('ix_packagings_is_deleted'), table_name='packagings')
    op.drop_index(op.f('ix_packagings_created_at'), table_name='packagings')
    op.drop_table('packagings')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_is_deleted'), table_name='locations')
    op.drop_index(op.f('ix_locations_created_at'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_conditions_name'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_is_deleted'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_created_at'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_deleted'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###